apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
    meta.helm.sh/release-name: kibana
    meta.helm.sh/release-namespace: ${namespace}
  labels:
    app.kubernetes.io/managed-by: Helm
  name: >-
    ${secret_name}-kibana
  namespace: ${namespace}
spec:
  parameters:
    cloudName: ''
    keyvaultName: ${keyvault_name}
    objects: |
      array:
        - |
          objectName: ${secret_name}
          objectType: secret
          objectVersion: ""
    tenantId: ${tenant_id}
    usePodIdentity: 'true'
    useVMManagedIdentity: 'false'
    userAssignedIdentityID: ''
  provider: azure
  secretObjects:
    - data:
        - key: tls.key
          objectName: ${secret_name}
        - key: tls.crt
          objectName: ${secret_name}
      secretName: ${secret_name}
      type: kubernetes.io/tls
