repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--hide providers
      #validate will exclude folders that contains xyz/test... and .utils that contains only scripts stuffs
      - id: terraform_validate
        exclude: '(.*\/tests|.utils)'
        args:
          - --args=-json
          - --args=-no-color
      - id: terraform_trivy
        args:
          - >
            --args=--format json
            --skip-dirs="**/.terraform"
