# values.yaml
global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 20s

# Common Configurations
commonConfig:
  nodeSelector: ${node_selector}
  tolerations: ${tolerations}
  defaultNodeAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/mode
            operator: NotIn
            values:
            - system

# AlertManager Configuration
alertmanager:
  enabled: true
  replicaCount: ${alertmanager_replicas}

  persistentVolume:
    enabled: true
    storageClass: ${storage_class_name}
    size: ${alertmanager_storage_size}

  # Security Context
  podSecurityContext:
    runAsUser: 65534
    runAsNonRoot: true
    fsGroup: 65534

  # Production Resource Requirements
  resources:
    requests:
      cpu: 200m      # Increased for production
      memory: 512Mi  # Increased for production
    limits:
      cpu: 500m      # Increased for production
      memory: 1Gi    # Increased for production

  # Configurable Affinity Rules
  affinity: ${alertmanager_affinity}

# Kube State Metrics Configuration
kube-state-metrics:
  enabled: true
  replicaCount: ${kube_state_metrics_replicas}

  # Production Resource Requirements
  resources:
    requests:
      cpu: 200m      # Increased for production
      memory: 256Mi  # Increased for production
    limits:
      cpu: 400m      # Increased for production
      memory: 512Mi  # Increased for production

  affinity: ${kube_state_metrics_affinity}

# Server Configuration
server:
  enabled: true
  replicaCount: ${server_replicas}

  configmapReload:
    enabled: true

  retention: "15d"
  retentionSize: "80GB"

  persistentVolume:
    enabled: true
    storageClass: ${storage_class_name}
    size: ${server_storage_size}

  # Security Context
  podSecurityContext:
    runAsUser: 65534
    runAsNonRoot: true
    fsGroup: 65534

  # Production Resource Requirements
  resources:
    requests:
      cpu: 1000m     # Increased for production
      memory: 4Gi    # Increased for production
    limits:
      cpu: 2000m     # Increased for production
      memory: 8Gi    # Increased for production

  affinity: ${server_affinity}

# Node Exporter Configuration
nodeExporter:
  enabled: true

  podSecurityContext:
    runAsUser: 65534
    runAsNonRoot: true
    fsGroup: 65534

  # Production Resource Requirements
  resources:
    requests:
      cpu: 200m      # Increased for production
      memory: 256Mi  # Increased for production
    limits:
      cpu: 400m      # Increased for production
      memory: 512Mi  # Increased for production

  tolerations: ${node_exporter_tolerations}

# Pushgateway Configuration
pushgateway:
  enabled: true
  replicaCount: ${pushgateway_replicas}

  # Production Resource Requirements
  resources:
    requests:
      cpu: 200m      # Increased for production
      memory: 256Mi  # Increased for production
    limits:
      cpu: 400m      # Increased for production
      memory: 512Mi  # Increased for production

  affinity: ${pushgateway_affinity}

# Security Configurations
rbac:
  create: true

networkPolicy:
  enabled: true

# Storage Configurations
storageClass: ${storage_class_name}
