version: "3.8"
services:
  azure-core-dns:
    image: ghcr.io/pagopa/azure-coredns-forwarder:v1.2.0@sha256:f7ee157abd4f9946819c60db45ef518cf063e37115b2b6a276ef990150cc7652
    container_name: dns-forwarder
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
