name: 🛃 Static Analysis PR

on:
  push:
    branches-ignore:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - run: |
          rm -rf *

      - name: 🔨 Get Modified Paths
        id: get-paths
        uses: pagopa/eng-github-actions-iac-template/global/get-modifed-folders@get-modified-folder-root-path-patch
        with:
          start_folder: "/"
          default_end_folder_depth: 2
          include_patterns: "/"

      - name: 👀 See folders downloaded
        if: env.dir_changes_detected == 'true'
        id: see
        shell: bash
        run: |
          ls -la
          du -h -d 3 .

      - name: run_init
        if: env.dir_changes_detected == 'true'
        run: |
          bash .utils/terraform_run_all.sh init docker

      - name: show_version
        if: env.dir_changes_detected == 'true'
        run: |
          TAG="v1.96.2@sha256:01f870b7689b5a09c1a370914fcddcac42c4b6478c9d369e1d2590dd0a66ffd0"
          docker run --rm --entrypoint cat ghcr.io/antonbabenko/pre-commit-terraform:$TAG /usr/bin/tools_versions_info

      - name: run_test
        if: env.dir_changes_detected == 'true'
        run: |
          TAG="v1.96.2@sha256:01f870b7689b5a09c1a370914fcddcac42c4b6478c9d369e1d2590dd0a66ffd0"
          docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a
