name: Static Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static_analysis:
    runs-on: ubuntu-22.04

    steps:
        # from https://github.com/actions/checkout/commits/main
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: run_init
        run: |
          bash .utils/terraform_run_all.sh init docker

      - name: show_version
        run: |
          TAG="v1.96.2@sha256:01f870b7689b5a09c1a370914fcddcac42c4b6478c9d369e1d2590dd0a66ffd0"
          docker run --rm --entrypoint cat ghcr.io/antonbabenko/pre-commit-terraform:$TAG /usr/bin/tools_versions_info

      - name: run_test
        run: |
          TAG="v1.96.2@sha256:01f870b7689b5a09c1a370914fcddcac42c4b6478c9d369e1d2590dd0a66ffd0"
          docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a
